[workspace]
channels = ["https://prefix.dev/glatzel", "conda-forge"]
name = "fornax"
platforms = ["win-64", "linux-64", "linux-aarch64", "osx-arm64"]

[dependencies]
libraw-dev = "==0.22.2"
maturin = "==1.15.0"
pip = "==26.2.1"
python = "3.13.*"

imageio = "==2.37.0"
lazy-loader = "==0.5"
msgspec = "==0.21.1"
nomkl = "==1.0"
numpy = "2.3.*"
numpydoc = "==1.10.0"
pydantic = "==2.13.5"

# test
pytest = "==9.1.1"
pytest-cov = "==7.1.0"
