[package]
name = "fornax-dalim"
version.workspace = true
edition.workspace = true

[[bench]]
harness = false
name = "linear"

[dependencies]
clerk.workspace = true
fornax-core.workspace = true
image.workspace = true
rayon.workspace = true
serde = { workspace = true, optional = true }

[dev-dependencies]
clerk = { workspace = true, features = ["tracing"] }
criterion.workspace = true
fornax-devtool.workspace = true
libraw.workspace = true
mischief.workspace = true

[features]
serde = ["dep:serde"]
