name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
  schedule:
    - cron: 0 16 * * *

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lefthook:
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/ci-lefthook.yml
    permissions:
      contents: write
      pull-requests: write
  cargo-doc:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-Dwarnings"
    steps:
      - parallel:
          - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
            with:
              submodules: true
          - uses: Glatzel/template/.github/actions/rust/setup-rust@b6b99ea17e01b640542095b6232d3ee5e3e7d4fd # v2026.8.30
          - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
            if: ${{github.event_name=='pull_request'}}
      - uses: Glatzel/template/.github/actions/rust/cargo-doc@b6b99ea17e01b640542095b6232d3ee5e3e7d4fd # v2026.8.30

  test-build:
    strategy:
      fail-fast: false
      matrix:
        machine: [windows-latest, ubuntu-latest, macos-latest, ubuntu-26.04-arm]
    env:
      dnc_version: 18_5
    runs-on: ${{matrix.machine}}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: restore dnc
        if: ${{runner.os != 'Linux'}}
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ./temp/dnc${{env.dnc_version}}*
          key: dnc-${{ runner.os }}-${{env.dnc_version}}
      - if: ${{runner.os != 'Linux'}}
        run: ./scripts/install-dnc.ps1 -version ${{env.dnc_version}}
        shell: pwsh
      - uses: Glatzel/template/.github/actions/rust/setup-rust@b6b99ea17e01b640542095b6232d3ee5e3e7d4fd # v2026.8.30
        with:
          toolchain: nightly
          components: clippy
      - uses: Glatzel/template/.github/actions/rust/cargo-clippy@b6b99ea17e01b640542095b6232d3ee5e3e7d4fd # v2026.8.30
      - uses: Glatzel/template/.github/actions/rust/cargo-test@b6b99ea17e01b640542095b6232d3ee5e3e7d4fd # v2026.8.30
        with:
          global-options: --workspace --all-features --exclude fornax-py
      - name: build
        run: |
          ./scripts/maturin-develop.ps1
        shell: pwsh
      - uses: Glatzel/template/.github/actions/python/pytest@b6b99ea17e01b640542095b6232d3ee5e3e7d4fd # v2026.8.30
        with:
          working-directory: ./crates/fornax-py
      - uses: Glatzel/template/.github/actions/common/codecov@b6b99ea17e01b640542095b6232d3ee5e3e7d4fd # v2026.8.30
        if: ${{ !cancelled() }}
  check-point:
    if: ( cancelled() || failure() ) && github.event_name == 'pull_request'
    needs: [ lefthook, cargo-doc, test-build]
    runs-on: ubuntu-slim
    steps:
      - run: exit 1
